/**
 * Tests for config.repo — uses Jest module mock to inject in-memory DB.
 *
 * Also tests integration with the Solaar parser (jsonToSolaarYaml).
 */

import Database from 'better-sqlite3';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const schema = readFileSync(resolve(__dirname, '../schema.sql'), 'utf-8');
const testDb = new Database(':memory:');
testDb.pragma('journal_mode = WAL');
testDb.pragma('foreign_keys = ON');
testDb.exec(schema);

jest.mock('../index', () => testDb);

import {
    saveConfig,
    saveConfigWithYaml,
    getConfigByProfile,
    getLatestConfig,
    getAllConfigs,
    markApplied,
    deleteConfigsByProfile,
} from '../repositories/config.repo';
import type { ProfileConfig } from '../../solaar/schema';

function makeProfileConfig(overrides: Partial<ProfileConfig> = {}): ProfileConfig {
    return {
        deviceId: 'dev-1',
        profile: 'default',
        buttons: [{
            id: 'Forward Button',
            actions: {
                click: { type: 'KeyPress', keys: ['Control_L', 'c'] },
                up: { type: 'KeyPress', keys: ['XF86_AudioPlay'] },
            },
        }],
        ...overrides,
    };
}

afterAll(() => testDb.close());

beforeEach(() => {
    testDb.exec('DELETE FROM configs; DELETE FROM profiles; DELETE FROM devices;');
    testDb.prepare(`INSERT INTO devices (id, name, displayName, metadata) VALUES ('dev-1', 'LIFT', 'Lift', '{}')`).run();
    testDb.prepare(`INSERT INTO profiles (id, deviceId, name, buttons, windowClasses) VALUES ('p-1', 'dev-1', 'Default', '[]', '[]')`).run();
});

describe('config.repo', () => {
    it('should save a config and auto-generate YAML via parser', () => {
        const config = makeProfileConfig();
        const result = saveConfig('p-1', config);

        expect(result.profileId).toBe('p-1');
        expect(result.jsonConfig).toEqual(config);
        // YAML should be generated by jsonToSolaarYaml
        expect(result.yamlConfig).toContain('%YAML 1.3');
        expect(result.yamlConfig).toContain('MouseGesture');
        expect(result.yamlConfig).toContain('Forward Button');
        expect(result.appliedAt).toBeNull();
    });

    it('should generate correct YAML for KeyPress actions', () => {
        const config = makeProfileConfig();
        const result = saveConfig('p-1', config);

        expect(result.yamlConfig).toContain('KeyPress');
        expect(result.yamlConfig).toContain('Control_L');
    });

    it('should save config with pre-generated YAML', () => {
        const config = makeProfileConfig();
        const customYaml = '# custom yaml\n---\nfoo: bar';

        const result = saveConfigWithYaml('p-1', config, customYaml);

        expect(result.yamlConfig).toBe(customYaml);
        expect(result.jsonConfig).toEqual(config);
    });

    it('should retrieve config by profile', () => {
        saveConfig('p-1', makeProfileConfig());

        const result = getConfigByProfile('p-1');
        expect(result).not.toBeNull();
        expect(result!.profileId).toBe('p-1');
        expect(result!.jsonConfig.buttons).toHaveLength(1);
    });

    it('should get latest config', () => {
        saveConfig('p-1', makeProfileConfig({ profile: 'first' }));
        // Small delay not needed — SQLite updatedAt is deterministic in tests
        saveConfig('p-1', makeProfileConfig({ profile: 'second' }));

        const latest = getLatestConfig();
        expect(latest).not.toBeNull();
    });

    it('should get all configs', () => {
        saveConfig('p-1', makeProfileConfig());
        saveConfig('p-1', makeProfileConfig({ profile: 'another' }));

        const all = getAllConfigs();
        expect(all.length).toBeGreaterThanOrEqual(2);
    });

    it('should mark config as applied', () => {
        const result = saveConfig('p-1', makeProfileConfig());

        expect(result.appliedAt).toBeNull();
        markApplied(result.id);

        const updated = getConfigByProfile('p-1');
        expect(updated!.appliedAt).toBeTruthy();
    });

    it('should delete configs by profile', () => {
        saveConfig('p-1', makeProfileConfig());
        saveConfig('p-1', makeProfileConfig());

        deleteConfigsByProfile('p-1');

        expect(getConfigByProfile('p-1')).toBeNull();
    });

    it('should return null for non-existent profile config', () => {
        expect(getConfigByProfile('nonexistent')).toBeNull();
    });

    it('should handle empty buttons config', () => {
        const config = makeProfileConfig({ buttons: [] });
        const result = saveConfig('p-1', config);

        expect(result.yamlConfig).toContain('%YAML 1.3');
        expect(result.jsonConfig.buttons).toHaveLength(0);
    });

    it('should roundtrip complex ProfileConfig through DB', () => {
        const config: ProfileConfig = {
            deviceId: 'dev-1',
            profile: 'gaming',
            buttons: [
                {
                    id: 'Forward Button',
                    actions: {
                        click: { type: 'KeyPress', keys: ['Control_L', 'c'] },
                        up: { type: 'KeyPress', keys: ['XF86_AudioPlay'] },
                        down: { type: 'MouseScroll', horizontal: 0, vertical: -5 },
                        left: { type: 'Execute', command: ['pactl', 'set-sink-volume', '@DEFAULT_SINK@', '-5%'] },
                        right: { type: 'MouseClick', button: 'middle', action: 'click' },
                    },
                },
                {
                    id: 'DPI Switch',
                    actions: {
                        click: { type: 'MouseClick', button: 'middle', action: 'click' },
                    },
                },
            ],
        };

        saveConfig('p-1', config);
        const loaded = getConfigByProfile('p-1')!;

        expect(loaded.jsonConfig.buttons).toHaveLength(2);
        expect(loaded.jsonConfig.buttons[0].id).toBe('Forward Button');
        expect(loaded.jsonConfig.buttons[0].actions.click).toEqual({ type: 'KeyPress', keys: ['Control_L', 'c'] });
        expect(loaded.jsonConfig.buttons[0].actions.down).toEqual({ type: 'MouseScroll', horizontal: 0, vertical: -5 });
        expect(loaded.jsonConfig.buttons[1].actions.click).toEqual({ type: 'MouseClick', button: 'middle', action: 'click' });
    });
});
