-- LogiTux persistence schema
-- Run once at server boot via db.exec()

CREATE TABLE IF NOT EXISTS devices (
    id          TEXT PRIMARY KEY,          -- unitId from Solaar
    name        TEXT NOT NULL,             -- solaarName
    displayName TEXT NOT NULL,
    model       TEXT,                      -- svgId
    image       TEXT,                      -- optional image path
    metadata    TEXT NOT NULL DEFAULT '{}', -- JSON: {pid, maxDpi, minDpi, dpiStep, battery, buttons[]}
    createdAt   TEXT NOT NULL DEFAULT (datetime('now')),
    updatedAt   TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS profiles (
    id            TEXT PRIMARY KEY,
    deviceId      TEXT NOT NULL REFERENCES devices(id),
    name          TEXT NOT NULL,
    appName       TEXT,                     -- windowClass for auto-switch
    isDefault     INTEGER NOT NULL DEFAULT 0,
    dpi           INTEGER,
    buttons       TEXT NOT NULL DEFAULT '[]', -- JSON: ButtonConfig[]
    windowClasses TEXT NOT NULL DEFAULT '[]', -- JSON: string[]
    createdAt     TEXT NOT NULL DEFAULT (datetime('now')),
    updatedAt     TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS configs (
    id          TEXT PRIMARY KEY,
    profileId   TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    jsonConfig  TEXT NOT NULL,              -- JSON: ProfileConfig (parser format)
    yamlConfig  TEXT NOT NULL,              -- YAML generated by jsonToSolaarYaml()
    appliedAt   TEXT,                       -- last time applied to Solaar
    updatedAt   TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS scripts (
    id          TEXT PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    path        TEXT NOT NULL,
    content     TEXT NOT NULL DEFAULT '',
    executable  INTEGER NOT NULL DEFAULT 1,
    createdAt   TEXT NOT NULL DEFAULT (datetime('now')),
    updatedAt   TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Indices
CREATE INDEX IF NOT EXISTS idx_profiles_deviceId ON profiles(deviceId);
CREATE INDEX IF NOT EXISTS idx_profiles_appName ON profiles(appName);
CREATE INDEX IF NOT EXISTS idx_configs_profileId ON configs(profileId);
